// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyABCDEFGHIJKLMNOPQRSTUVWXYZ1234567',
    appId: '1:123456789012:web:abcdef1234567890abcdef',
    messagingSenderId: '123456789012',
    projectId: 'falconlog-app',
    authDomain: 'falconlog-app.firebaseapp.com',
    storageBucket: 'falconlog-app.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDN6eriw8_kPn1EfKaWEGH_WnZ5W5FNZQI',
    appId: '1:441066678931:android:57941aefd7014c804d7b66',
    messagingSenderId: '441066678931',
    projectId: 'falconlog-534f8',
    storageBucket: 'falconlog-534f8.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAh6SJhDrgW7r66RjK_is7UQUVBLV4IZZE',
    appId: '1:441066678931:ios:fee5918766cfc8304d7b66',
    messagingSenderId: '441066678931',
    projectId: 'falconlog-534f8',
    storageBucket: 'falconlog-534f8.firebasestorage.app',
    iosBundleId: 'com.falconlog.falconlog',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyABCDEFGHIJKLMNOPQRSTUVWXYZ1234567',
    appId: '1:123456789012:macos:abcdef1234567890abcdef',
    messagingSenderId: '123456789012',
    projectId: 'falconlog-app',
    storageBucket: 'falconlog-app.appspot.com',
    iosBundleId: 'com.falcon_log.falconlog',
  );
}