"""Sync Android notification icon vector from assets/ic_notification_source.svg."""
from __future__ import annotations

import re
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
SVG_SRC = ROOT / "assets" / "ic_notification_source.svg"
DRAWABLE_XML = (
    ROOT / "android" / "app" / "src" / "main" / "res" / "drawable" / "ic_notification.xml"
)
RES = ROOT / "android" / "app" / "src" / "main" / "res"

DENSITY_FOLDERS = (
    "drawable-mdpi",
    "drawable-hdpi",
    "drawable-xhdpi",
    "drawable-xxhdpi",
    "drawable-xxxhdpi",
)

LEGACY_PNG_NAMES = (
    "ic_notification.png",
    "ic_falconlog_notification.png",
    "ic_falconlog_notification_large.png",
)


def _extract_path_data(svg_text: str) -> str:
    match = re.search(r'<path[^>]+d="([^"]+)"', svg_text)
    if not match:
        raise RuntimeError(f"Could not find path in {SVG_SRC}")
    return match.group(1).strip()


def _build_vector_xml(path_data: str) -> str:
    return f"""<?xml version="1.0" encoding="utf-8"?>
<!-- Generated by generate_notification_icons.py from ic_notification_source.svg. -->
<vector xmlns:android="http://schemas.android.com/apk/res/android"
    android:width="24dp"
    android:height="24dp"
    android:viewportWidth="24"
    android:viewportHeight="24">
    <path
        android:fillColor="#FFFFFFFF"
        android:pathData="{path_data}" />
</vector>
"""


def _remove_density_pngs() -> None:
    for folder in DENSITY_FOLDERS:
        target_dir = RES / folder
        if not target_dir.exists():
            continue
        for name in LEGACY_PNG_NAMES:
            path = target_dir / name
            if path.exists():
                path.unlink()
                print(f"Removed {path}")


def main() -> None:
    if not SVG_SRC.exists():
        raise FileNotFoundError(f"Missing SVG source: {SVG_SRC}")

    svg_text = SVG_SRC.read_text(encoding="utf-8")
    path_data = _extract_path_data(svg_text)
    DRAWABLE_XML.parent.mkdir(parents=True, exist_ok=True)
    DRAWABLE_XML.write_text(_build_vector_xml(path_data), encoding="utf-8")
    _remove_density_pngs()
    print(f"Wrote {DRAWABLE_XML}")
    print("Use @drawable/ic_notification in Dart; circle color from Color(0xFF3949AB).")


if __name__ == "__main__":
    main()
